## The following program is derived from the git hub account

## https://github.com/rdpeng/ProgrammingAssignment2
## From the README.md file.


###################################################################################################
###################################################################################################
###################################################################################################
###################################################################################################
###################################################################################################
###################################################################################################
###################################################################################################
###################################################################################################
###################################################################################################
#The follow programs and comments were generated by basiclly subsituding 
#solve or Solve("solve()" finds the Inverse) for mean and matrix for Vector
###################################################################################################
###################################################################################################
###################################################################################################
###################################################################################################
###################################################################################################
###################################################################################################
###################################################################################################
###################################################################################################
###################################################################################################
###################################################################################################






##The following function calculates the inverse of the special "matrix"
##created with the above function. However, it first checks to see if the
##inverse has already been calculated. If so, it `get`s the inverse from the
##cache and skips the computation. Otherwise, it calculates the inverse of
##the data and sets the value of the inverse in the cache via the `setsolve`
##function.



### Assignment: Caching the Inverse of a Matrix


###################################################################################################
###################################################################################################
###################################################################################################
###################################################################################################
#######         Form For CacheMatrix.R  Required by Program 2 Requirements  Below #################
###################################################################################################
###################################################################################################
###################################################################################################
###################################################################################################
###################################################################################################


##Caching the Inverse(using "solve()") of a Matrix

##In this example we use the `<<-` operator which can be used to
##assign a value to an object in an environment that is different from the
##current environment. Below are two functions that are used to create a
##special object that stores a numeric matrix  and caches its inverse.
##
##The first function, `makeMatrix` creates a special "matrix", which is
##really a list containing a function to
##
##1.  set the value of the matrix
##2.  get the value of the matrix
##3.  set the value of the inverse("solve()")
##4.  get the value of the inverse






makeCacheMatrix <- function(x = matrix()) {
            m <- NULL
            set <- function(y) {
                    x <<- y
                    m <<- NULL
            }
            get <- function() x
            setsolve <- function(solve) m <<- solve
            getsolve <- function() m
            list(set = set, get = get,
                 setsolve = setsolve,
                 getsolve = getsolve)
    }






##The following function calculates the inverse of the special "matrix"
##created with the above function. However, it first checks to see if the
##inverse has already been calculated. If so, it `get`s the inverse from the
##cache and skips the computation. Otherwise, it calculates the inverse of
##the data and sets the value of the inverse in the cache via the `setsolve`
##function.
        
## Return a matrix that is the inverse of 'x'
###    cachesolve <- function(x, ...) {
cacheSolve <- function(x, ...) {
            m <- x$getsolve()
            if(!is.null(m)) {
                    message("getting cached data")
                    return(m)
            }
            data <- x$get()
            m <- solve(data, ...)
            x$setsolve(m)
            m
    }


###################################################################################################
###################################################################################################
###################################################################################################
###################################################################################################
#######         Form For CacheMatrix.R  Required by Program 2 Requirements  Above #################
###################################################################################################
###################################################################################################
###################################################################################################
###################################################################################################



##The Code below is intended to aid in testing.

##TestProgram2
##When printing matrics times are not printed
## Note the random matrix may not be invertable
testprogram<-function(dimOfSqureMatrix=1000,printmatrics=FALSE){
set.seed(0)
sq<-dimOfSqureMatrix^2
vec<-rnorm(sq)
matx<-matrix(vec,nrow=dimOfSqureMatrix,ncol = dimOfSqureMatrix)
if(printmatrics){
        print("matx")
        print(matx)
        print("")
}

##print(matx)
matxCached<-NULL
if(printmatrics){
        print(matxCached)
        print(matxCached)
        print("")
}



matxCached<-makeCacheMatrix(matx)
atime<-Sys.time()
inverseMatrix<-cacheSolve(matxCached)

if(printmatrics){
        print("inverseMatrix")
        print(inverseMatrix)
        print(" ")
}

btime<-Sys.time()
inverseMatrix<-cacheSolve(matxCached)
ctime<-Sys.time()

if(printmatrics){
print("inverseMatrix")
print(inverseMatrix)
print(" ")
}

if(!printmatrics){
print("Before first cacheSolve")
print(atime)
print(" ")
print("After first cacheSolve")
print(btime)
print(" ")
print("After second cacheSolve")
print(ctime)
}



#print(inverseMatrix%*%matx)
}

testprogram(4,printmatrics=TRUE)
testprogram(1000)






##Matrix inversion is usually a costly computation and there may be some
##benefit to caching the invx.Ricachematrix.Rerse of a matrix rather than computing it
##repeatedly (there are also alternatives to matrix inversion that we will
##not discuss here). Your assignment is to write a pair of functions that
##cache the inverse of a matrix.
##
##Write the following functions:
##
##1.  `makeCacheMatrix`: This function creates a special "matrix" object
##    that can cache its inverse.
##2.  `cacheSolve`: This function computes the inverse of the special
##    "matrix" returned by `makeCacheMatrix` above. If the inverse has
##    already been calculated (and the matrix has not changed), then
##    `cacheSolve` should retrieve the inverse from the cache.
##
##Computing the inverse of a square matrix can be done with the `solve`
##function in R. For example, if `X` is a square invertible matrix, then
##`solve(X)` returns its inverse.
##
##For this assignment, assume that the matrix supplied is always
##invertible.
##
##In order to complete this assignment, you must do the following:
##
##1.  Fork the GitHub repository containing the stub R files at
##    [https://github.com/rdpeng/ProgrammingAssignment2](https://github.com/rdpeng/ProgrammingAssignment2)
##    to create a copy under your own account.
##2.  Clone your forked GitHub repository to your computer so that you can
##    edit the files locally on your own machine.
##3.  Edit the R file contained in the git repository and place your
##    solution in that file (please do not rename the file).
##4.  Commit your completed R file into YOUR git repository and push your
##    git branch to the GitHub repository under your account.
##5.  Submit to Coursera the URL to your GitHub repository that contains
##    the completed R code for the assignment.
##
##### Grading
##
##This assignment will be graded via peer assessment.
